In [30]:
import pandas as pd

In [31]:
df = pd.read_spss("C:/Users/njoro/Downloads/Survey (to share).sav")

In [32]:
df.head()

,id,consent,screen,gen_m,gen_f,gen_nb,gen_na,age,eth_ab,eth_ea,...,contrib_mature_pres,contrib_res_past,contrib_exp_past,contrib_pickup_past,inc_credit,inc_prize,inc_na,inc_o,willing_o,total_time
0,187.0,Yes,Yes,Yes,No,No,No,25 to 34,No,No,...,Agree,,,,Yes,Yes,No,,,492.09
1,58.0,Yes,Yes,No,Yes,No,No,45 to 54,No,No,...,Agree,,,,Yes,Yes,No,,,561.00
2,68.0,Yes,Yes,No,Yes,No,No,35 to 44,No,No,...,Agree,,,,Yes,Yes,No,,,610.61
3,96.0,Yes,Yes,No,Yes,No,No,35 to 44,No,No,...,Strongly Agree,,,,Yes,Yes,No,,,649.99
4,61.0,Yes,Yes,No,Yes,No,No,35 to 44,No,No,...,Strongly Agree,,,,Yes,Yes,No,,,748.92

In [33]:
df.replace('N/A', -999, inplace=True)
df.replace('Prefer not to answer', -777, inplace=True)

In [34]:

# Mapping dictionaries
yes_no_map = {'Yes': 1, 'No': 0}
age_map = {
    '18 to 24': 1, '25 to 34': 2, '35 to 44': 3, '45 to 54': 4, 
    '55 to 64': 5, '65 or over': 6, 'Prefer not to answer': -777
}
num_child_map = {
    '1': 1, '2': 2, '3': 3, '4': 4, '5 or more': 5, 'Prefer not to answer': -777
}
yes_no_na_map = {'Yes': 1, 'No': 0, 'N/A': -999}

yes_no_pref = {'Yes': 1, 'No': 0, 'Prefer not to answer': 3}

parent_map = {'Yes': 1, 'No': 2, 'I don’t know (e.g., I never asked my parents, or they never told me)': 3, 'I didn’t make art as a child':4
    }

imp_bond_map = {
    'Strongly Disagree': 1, 'Disagree': 2, 'Agree': 3, 'Strongly Agree': 4
}

keep_pres_map = {
    'I keep all of it (or most of it)': 1, 'I keep a lot of it (but not most)': 2,
    'I keep very little of it (e.g., exclusively their “best” pieces)': 3,
    'I don’t keep any of it': 4, 'I don’t know': 5
}



keep_past_map = {
    'I keep all of it (or most of it)': 1, 'I keep a lot of it (but not most)': 2,
    'I keep very little of it (e.g., exclusively their “best” pieces)': 3,
    'I haven’t kept any of it': 4, 'I don’t know': 5
}


cdic_int_map = {
    'Not interested at all': 1, 'Not very interested': 2, 
    'Somewhat interested': 3, 'Very interested': 4
}


rank_pres_map = {
    'The artwork’s overall appearance and aesthetic value': 1,
    'The artwork’s subject or theme (e.g., nature)': 2,
    'The medium or technique used to create the artwork': 3,
    'The creativity/uniqueness of the artwork': 4,
    'The artwork reflects my child’s personality/mood': 5,
    'I want to track my child’s development/progression in art': 6,
    'My child has an emotional connection to the artwork (e.g., captures an important moment/memory, nostalgia)': 7,
    'I have an emotional connection to the artwork (e.g., captures an important moment/memory, nostalgia)': 8,
    'A family member (other than my child or me) has an emotional connection to the artwork (e.g., captures an important moment/memory, nostalgia)': 9,
    'My child requests that the artwork is saved': 10
}


rank_past_map = {
    'The artwork’s overall appearance and aesthetic value': 1,
    'The artwork’s subject or theme (e.g., nature)': 2,
    'The medium or technique used to create the artwork': 3,
    'The creativity/uniqueness of the artwork': 4,
    'The artwork reflected my child’s personality/mood': 5,
    'I wanted to track my child’s development/progression in art': 6,
    'My child had an emotional connection to the artwork (e.g., captured an important moment/memory, nostalgia)': 7,
    'I had an emotional connection to the artwork (e.g., captured an important moment/memory, nostalgia)': 8,
    'A family member (other than my child or me) had an emotional connection to the artwork (e.g., captured an important moment/memory, nostalgia)': 9,
    'My child requested that the artwork was saved': 10
}


rank_motiv_map = {
    'My child would want to submit their artwork': 1,
    'I would want my child’s art to be recognized': 2,
    'It would boost my child’s self-esteem and encourage them to create more artwork and develop their art skills': 3,
    'I would want to contribute to research and education related to children’s artwork': 4,
    'I would want to contribute to the preservation of children’s artistic expression': 5,
    'It would save me from having to store my child’s artwork at home': 6
}


cdic_sub_map = {
    'I would submit any and all artwork (I want all of my child’s artwork to be included in the CDIC archive)': 1,
    'I would only submit the artwork that we liked the most (I only want my child’s best artwork to be included in the CDIC archive)': 2,
    'I would submit some of the artwork, but I would keep the artwork that we liked the most within the family (I want to contribute to the CDIC archive, but I want to keep my child’s best artwork within the family)': 3,
    'I would contribute my child’s artwork under specific conditions not mentioned above (specify)': 4,
    'I would not submit any artwork (I am not interested in contributing to the CDIC archive)': 5
}



# Apply mappings to columns
columns_to_map = {
    'consent': yes_no_map,
    'screen': yes_no_map,
    'gen_m': yes_no_map,
    'gen_f': yes_no_map,
    'gen_nb': yes_no_map,
    'gen_na': yes_no_map,
    'eth_ab': yes_no_map,
    'eth_ea': yes_no_map,
    'eth_ew': yes_no_map,
    'eth_indox': yes_no_map,
    'eth_lat': yes_no_map,
    'eth_pol': yes_no_map,
    'eth_sa': yes_no_map,
    'eth_sea': yes_no_map,
    'eth_wa': yes_no_map,
    'eth_indig': yes_no_map,
    'eth_na': yes_no_map,
    'age': age_map,
    'num_child': num_child_map,
    'child_18up': yes_no_map,
    'agec_0_4': yes_no_map,
    'agec_5_11': yes_no_map,
    'agec_12_17': yes_no_map,
    'agec_18_up': yes_no_map,
    'agec_na': yes_no_map,
    'store_dev_pres': yes_no_map,
    'store_cloud_pres': yes_no_map,
    'store_socmed_pres': yes_no_map,
    'store_phys_pres': yes_no_map,
    'store_dev_past': yes_no_map,
    'store_cloud_past': yes_no_map,
    'store_socmed_past': yes_no_map,
    'store_phys_past': yes_no_map,
    'keepnot_space_pres': yes_no_map,
    'keepnot_busy_pres': yes_no_map,
    'keepnot_fam_pres': yes_no_map,
    'keepnot_cult_pres': yes_no_map,
    'keepnot_child_pres': yes_no_map,
    'keepnot_space_past': yes_no_map,
    'keepnot_busy_past': yes_no_map,
    'keepnot_fam_past': yes_no_map,
    'keepnot_cult_past': yes_no_map,
    'keepnot_child_past': yes_no_map,
    'barr_space_pres': yes_no_map,
    'barr_busy_pres': yes_no_map,
    'barr_fam_pres': yes_no_map,
    'barr_cult_pres': yes_no_map,
    'barr_child_pres': yes_no_map,
    'barr_space_past': yes_no_map,
    'barr_busy_past': yes_no_map,
    'barr_fam_past': yes_no_map,
    'barr_cult_past': yes_no_map,
    'barr_child_past': yes_no_map,
    'disc_priv': yes_no_na_map,
    'disc_child': yes_no_na_map,
    'disc_contrib': yes_no_na_map,
    'disc_moreinfo': yes_no_na_map,
    'disc_novalue': yes_no_na_map,
    'disc_busy': yes_no_na_map,
    'inc_credit': yes_no_na_map,
    'inc_prize': yes_no_na_map,
    'inc_na': yes_no_na_map,
    'art_es': yes_no_map,
    'art_hs': yes_no_map,
    'art_uni': yes_no_map,
    'art_grad': yes_no_map,
    'art_job': yes_no_map,
    'art_teach': yes_no_map,
    'art_ft': yes_no_map,
    'art_app': yes_no_map,
    'parents_save': parent_map,
    'imp_bond': imp_bond_map,
    'imp_dev': imp_bond_map,
    'imp_se': imp_bond_map,
    'imp_ec': imp_bond_map,
    'imp_childhood': imp_bond_map,
    'imp_soc': imp_bond_map,
    'imp_not': imp_bond_map,
    'contrib_res_pres': imp_bond_map,
    'contrib_exp_pres': imp_bond_map,
    'contrib_pickup_pres': imp_bond_map,
    'contrib_mature_pres': imp_bond_map,
    'contrib_res_past': imp_bond_map,
    'contrib_exp_past': imp_bond_map,
    'contrib_pickup_past': imp_bond_map,
    'keep_pres': keep_pres_map,
    'keep_past': keep_past_map,
    'rank1keep_pres': rank_pres_map,
    'rank2keep_pres': rank_pres_map,
    'rank3keep_pres': rank_pres_map,
    'rank1keep_past': rank_past_map,
    'rank2keep_past': rank_past_map,
    'rank3keep_past': rank_past_map,
    'cdic_int': cdic_int_map,
    'rank1_motiv': rank_motiv_map,
    'rank2_motiv': rank_motiv_map,
    'rank3_motiv': rank_motiv_map,
    'rank4_motiv': rank_motiv_map,
    'rank5_motiv': rank_motiv_map,
    'rank6_motiv': rank_motiv_map,
    'cdic_sub': cdic_sub_map,
}

# Apply mappings to the appropriate columns
for col, mapping in columns_to_map.items():
    if col in df.columns:
        df[col] = df[col].map(mapping)

In [35]:
df.head()

,id,consent,screen,gen_m,gen_f,gen_nb,gen_na,age,eth_ab,eth_ea,...,contrib_mature_pres,contrib_res_past,contrib_exp_past,contrib_pickup_past,inc_credit,inc_prize,inc_na,inc_o,willing_o,total_time
0,187.0,1,1,1,0,0,0,2,0,0,...,3.0,NaN,NaN,NaN,1.0,1.0,0,,,492.09
1,58.0,1,1,0,1,0,0,4,0,0,...,3.0,NaN,NaN,NaN,1.0,1.0,0,,,561.00
2,68.0,1,1,0,1,0,0,3,0,0,...,3.0,NaN,NaN,NaN,1.0,1.0,0,,,610.61
3,96.0,1,1,0,1,0,0,3,0,0,...,4.0,NaN,NaN,NaN,1.0,1.0,0,,,649.99
4,61.0,1,1,0,1,0,0,3,0,0,...,4.0,NaN,NaN,NaN,1.0,1.0,0,,,748.92

In [36]:
print(df)

        id  consent  screen  gen_m  gen_f  gen_nb  gen_na  age  eth_ab  \
0    187.0        1       1      1      0       0       0    2       0
1     58.0        1       1      0      1       0       0    4       0
2     68.0        1       1      0      1       0       0    3       0
3     96.0        1       1      0      1       0       0    3       0
4     61.0        1       1      0      1       0       0    3       0
..     ...      ...     ...    ...    ...     ...     ...  ...     ...
108   13.0        1       1      0      1       0       0    3       0
109   83.0        1       1      0      1       0       0    5       0
110   41.0        1       1      0      1       0       0    2       0
111   54.0        1       1      1      0       0       0    4       0
112   74.0        1       1      0      1       0       0    3       0

     eth_ea  ...  contrib_mature_pres  contrib_res_past  contrib_exp_past  \
0         0  ...                  3.0               NaN               NaN
1         0  ...                  3.0               NaN               NaN
2         0  ...                  3.0               NaN               NaN
3         0  ...                  4.0               NaN               NaN
4         0  ...                  4.0               NaN               NaN
..      ...  ...                  ...               ...               ...
108       0  ...                  NaN               3.0               3.0
109       0  ...                  NaN               3.0               3.0
110       0  ...                  NaN               3.0               3.0
111       0  ...                  NaN               3.0               3.0
112       0  ...                  NaN               3.0               1.0

     contrib_pickup_past  inc_credit  inc_prize  inc_na  inc_o  \
0                    NaN         1.0        1.0       0
1                    NaN         1.0        1.0       0
2                    NaN         1.0        1.0       0
3                    NaN         1.0        1.0       0
4                    NaN         1.0        1.0       0
..                   ...         ...        ...     ...    ...
108                  3.0         1.0        1.0       0
109                  3.0         1.0        1.0       0
110                  3.0         1.0        1.0       0
111                  3.0         1.0        0.0       0
112                  2.0         1.0        0.0       0

                                             willing_o total_time
0                                                          492.09
1                                                          561.00
2                                                          610.61
3                                                          649.99
4                                                          748.92
..                                                 ...        ...
108  If the archive has a system of providing certi...    1376.68
109                                                       1377.62
110                          Having a digital copy you    1598.98
111                                                       1695.24
112                                                       1922.92

[113 rows x 123 columns]

In [38]:
import pyreadstat

# Save the cleaned data back to SPSS file
pyreadstat.write_sav(df, 'Data.sav')

In [39]:
df.replace('NaN', -999, inplace=True)

In [40]:
print(df)

        id  consent  screen  gen_m  gen_f  gen_nb  gen_na  age  eth_ab  \
0    187.0        1       1      1      0       0       0    2       0
1     58.0        1       1      0      1       0       0    4       0
2     68.0        1       1      0      1       0       0    3       0
3     96.0        1       1      0      1       0       0    3       0
4     61.0        1       1      0      1       0       0    3       0
..     ...      ...     ...    ...    ...     ...     ...  ...     ...
108   13.0        1       1      0      1       0       0    3       0
109   83.0        1       1      0      1       0       0    5       0
110   41.0        1       1      0      1       0       0    2       0
111   54.0        1       1      1      0       0       0    4       0
112   74.0        1       1      0      1       0       0    3       0

     eth_ea  ...  contrib_mature_pres  contrib_res_past  contrib_exp_past  \
0         0  ...                  3.0               NaN               NaN
1         0  ...                  3.0               NaN               NaN
2         0  ...                  3.0               NaN               NaN
3         0  ...                  4.0               NaN               NaN
4         0  ...                  4.0               NaN               NaN
..      ...  ...                  ...               ...               ...
108       0  ...                  NaN               3.0               3.0
109       0  ...                  NaN               3.0               3.0
110       0  ...                  NaN               3.0               3.0
111       0  ...                  NaN               3.0               3.0
112       0  ...                  NaN               3.0               1.0

     contrib_pickup_past  inc_credit  inc_prize  inc_na  inc_o  \
0                    NaN         1.0        1.0       0
1                    NaN         1.0        1.0       0
2                    NaN         1.0        1.0       0
3                    NaN         1.0        1.0       0
4                    NaN         1.0        1.0       0
..                   ...         ...        ...     ...    ...
108                  3.0         1.0        1.0       0
109                  3.0         1.0        1.0       0
110                  3.0         1.0        1.0       0
111                  3.0         1.0        0.0       0
112                  2.0         1.0        0.0       0

                                             willing_o total_time
0                                                          492.09
1                                                          561.00
2                                                          610.61
3                                                          649.99
4                                                          748.92
..                                                 ...        ...
108  If the archive has a system of providing certi...    1376.68
109                                                       1377.62
110                          Having a digital copy you    1598.98
111                                                       1695.24
112                                                       1922.92

[113 rows x 123 columns]

In [41]:
# Save the cleaned data back to SPSS file
pyreadstat.write_sav(df, 'Cleaned.sav')